name: oci-image

on:
  push:
    branches: 
    - main
    tags:
    - "v*"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: DockerTag
        id: docker-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            rustrial/aws-eks-iam-auth-controller:${{ steps.docker-tag.outputs.tag }}
  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
    - main
    strategy:
      matrix:
        k8s:
          - v1.18.8
          - v1.19.1
          - v1.20.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: DockerTag
        id: docker-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.0
      - name: Run chart-testing (lint)
        run: (cd charts/rustrial-aws-eks-iam-auth-controller && helm lint .)
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.1.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Install chart
        run: (cd charts/rustrial-aws-eks-iam-auth-controller && helm install aws-eks-iam-auth-controller . --wait --set-string image.tag=${{ steps.docker-tag.outputs.tag }})
